name: Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  cmake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install JUCE build deps (Ubuntu)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential ninja-build cmake pkg-config \
            libasound2-dev libfreetype6-dev libfontconfig1-dev \
            libx11-dev libxcomposite-dev libxcursor-dev libxinerama-dev libxrandr-dev \
            mesa-common-dev libglu1-mesa-dev \
            libcurl4-openssl-dev \
            libgtk-3-dev libglib2.0-dev
          # WebKit: 22.04 uses 4.0; 24.04 uses 4.1
          if apt-cache show libwebkit2gtk-4.0-dev >/dev/null 2>&1; then
            sudo apt-get install -y libwebkit2gtk-4.0-dev
          else
            sudo apt-get install -y libwebkit2gtk-4.1-dev
          fi
          # Sanity check (optional): print GTK cflags so we know pkg-config sees it
          pkg-config --cflags gtk+-3.0 || true

      - name: Clean previous build (force re-detect of deps)
        run: rm -rf build

      - name: Configure
        run: cmake -S . -B build -G Ninja -DBROADCASTMIX_BUILD_TESTS=ON -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Run smoke tests
        run: ctest --test-dir build --output-on-failure

